name: "Badge generator"
author: "Andrii Leonov"
description: "Generates badge image and return path to it"
branding:
  icon: "git-branch"
  color: "white"
inputs:
  percentage:
    descrpition: Badge percentage from 0 to 100
    required: true
    default: 0%
  title:
    descrpition: Badge title
    required: false
    default: Coverage
  color:
    description: Badge color
    required: false
    default: green
outputs:
  badge-path:
    description: Generated badge path
    value: ${{ steps.badge-generator.outputs.badge-path }}
runs:
  using: "composite"
  steps:
    - name: Install Badge Generator
      shell: bash
      run: npm install -g badge-maker

    - name: Transform percentage
      id: transform_percentage
      shell: bash
      env:
        PERCENTAGE: ${{ inputs.percentage }}
      run: |
        echo "percentage=$(echo "$PERCENTAGE" | grep -o -E '[0-9]+')" >> $GITHUB_OUTPUT

# colors: https://www.npmjs.com/package/badge-maker
    - name: Determine color
      id: determine_color
      shell: bash
      env:
        TRANSFORMED_PERCENTAGE: ${{ steps.transform_percentage.outputs.percentage }}
      run: |
        if [ $TRANSFORMED_PERCENTAGE > 90 ] ; then
          color = "green"
        elif [ $TRANSFORMED_PERCENTAGE > 80 ] ; then
          color = "yellowgreen"
        elif [ $TRANSFORMED_PERCENTAGE > 65 ] ; then
          color = "orange"
        else
          color = "inactive"
        fi
        echo "color=${color}" >> $GITHUB_OUTPUT

    - name: Generate badge
      id: badge-generator
      shell: bash
      env:
        TITLE: ${{ inputs.title }}
        PERCENTAGE: ${{ inputs.percentage }}
        COLOR: ${{ steps.determine_color.outputs.color }}
      run: |
        npx badge-maker "$TITLE" "$PERCENTAGE" "$COLOR" > badge.svg
        echo "badge-path=$(realpath badge.svg)" >> $GITHUB_OUTPUT
