name: "Badge generator"
author: "Andrii Leonov"
description: "Generates badge image and return path to it"
branding:
  icon: "git-branch"
  color: "white"
inputs:
  percentage:
    descrpition: Badge percentage from 0 to 100
    required: true
    default: 0%
  title:
    descrpition: Badge title
    required: false
    default: Coverage
  color:
    description: Badge color
    required: false
    default: green
outputs:
  badge-path:
    description: Generated badge path
    value: ${{ steps.badge-generator.outputs.badge-path }}
runs:
  using: "composite"
  steps:
    - name: Install Badge Generator
      shell: bash
      run: npm install -g badge-maker

    - name: Generate badge
      id: badge-generator
      shell: bash
      env:
        TITLE: ${{ inputs.title }}
        PERCENTAGE: ${{ inputs.percentage }}
        COLOR: ${{ inputs.color }}
      run: |
        npx badge-maker "$TITLE" "$PERCENTAGE" "$COLOR" > badge.svg
        echo "badge-path=$(realpath badge.svg)" >> $GITHUB_OUTPUT
